const MAX_ROMAN_NUMERAL = 3999;
const MAX_TO_ROMAN_NUMERAL = 1000000;
const ROMAN_NUMERAL_ENTRY = 'ROMAN-NUMERAL';
const ARABIC_NUMERAL_ENTRY = 'HINDU-ARABIC';

export { ARABIC_NUMERAL_ENTRY, MAX_ROMAN_NUMERAL, MAX_TO_ROMAN_NUMERAL, ROMAN_NUMERAL_ENTRY };
